project_id = "betztvhkxnazfeeleqnf"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.notify-shipment-created]
verify_jwt = false

[functions.currency-context]
verify_jwt = false

[functions.send-shipment-notification]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.check-email-exists]
verify_jwt = false

[functions.send-campaign]
verify_jwt = true

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.email-track]
verify_jwt = false

[functions.email-unsubscribe]
verify_jwt = false
