import { useEffect, useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import DashboardLayout from "@/components/dashboard/DashboardLayout";
import { ShipmentsListSkeleton } from "@/components/dashboard/DashboardSkeletons";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { useWalletBalance } from "@/hooks/useWalletBalance";
import PayShipmentDialog from "@/components/shipments/PayShipmentDialog";
import {
  Package,
  Plus,
  Search,
  Truck,
  Clock,
  CheckCircle,
  AlertCircle,
  MapPin,
  Calendar,
  DollarSign,
  Wallet,
} from "lucide-react";

interface Shipment {
  id: string;
  tracking_number: string;
  origin_country: string;
  origin_city: string;
  destination_country: string;
  destination_city: string;
  weight: number;
  service_type: string;
  status: string;
  estimated_delivery: string | null;
  description: string | null;
  created_at: string;
  price: number | null;
  payment_status: string;
}

const countries = [
  "United States", "United Kingdom", "Germany", "France", "China", 
  "Japan", "Australia", "Canada", "Nigeria", "UAE", "Singapore", "India"
];

const serviceTypes = [
  { id: "air-express", name: "Air Express" },
  { id: "air-standard", name: "Air Standard" },
  { id: "ocean-fcl", name: "Ocean FCL" },
  { id: "ocean-lcl", name: "Ocean LCL" },
];

const Shipments = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const { balance, refetch: refetchBalance } = useWalletBalance(user?.id);
  const [shipments, setShipments] = useState<Shipment[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [paymentDialogOpen, setPaymentDialogOpen] = useState(false);
  const [selectedShipment, setSelectedShipment] = useState<Shipment | null>(null);

  const [formData, setFormData] = useState({
    origin_country: "",
    origin_city: "",
    destination_country: "",
    destination_city: "",
    weight: "",
    service_type: "",
    description: "",
  });

  useEffect(() => {
    fetchShipments();
  }, [user]);

  const fetchShipments = async () => {
    if (!user) return;

    const { data, error } = await supabase
      .from("shipments")
      .select("*")
      .eq("user_id", user.id)
      .order("created_at", { ascending: false });

    if (error) {
      toast({
        title: "Error",
        description: "Failed to fetch shipments",
        variant: "destructive",
      });
    } else {
      setShipments(data || []);
    }
    setLoading(false);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;

    setIsSubmitting(true);

    const estimatedDays = formData.service_type.includes("express") ? 3 : 
                          formData.service_type.includes("ocean") ? 25 : 7;
    const estimatedDelivery = new Date();
    estimatedDelivery.setDate(estimatedDelivery.getDate() + estimatedDays);

    const { error } = await supabase.from("shipments").insert({
      user_id: user.id,
      origin_country: formData.origin_country,
      origin_city: formData.origin_city,
      destination_country: formData.destination_country,
      destination_city: formData.destination_city,
      weight: parseFloat(formData.weight),
      service_type: formData.service_type,
      description: formData.description || null,
      status: "pending",
      estimated_delivery: estimatedDelivery.toISOString().split("T")[0],
      tracking_number: "", // Will be auto-generated by trigger
    });

    if (error) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } else {
      toast({
        title: "Shipment Created",
        description: "Your shipment has been created successfully.",
      });
      setIsDialogOpen(false);
      setFormData({
        origin_country: "",
        origin_city: "",
        destination_country: "",
        destination_city: "",
        weight: "",
        service_type: "",
        description: "",
      });
      fetchShipments();
    }

    setIsSubmitting(false);
  };

  const getStatusBadge = (status: string) => {
    const statusConfig: Record<string, { variant: "default" | "secondary" | "destructive" | "outline"; icon: any; color: string }> = {
      pending: { variant: "secondary", icon: Clock, color: "text-warning" },
      in_transit: { variant: "default", icon: Truck, color: "text-blue-500" },
      delivered: { variant: "outline", icon: CheckCircle, color: "text-success" },
      cancelled: { variant: "destructive", icon: AlertCircle, color: "text-destructive" },
    };
    const config = statusConfig[status] || statusConfig.pending;
    const Icon = config.icon;
    return (
      <Badge variant={config.variant} className="gap-1 capitalize">
        <Icon className="w-3 h-3" />
        {status.replace("_", " ")}
      </Badge>
    );
  };

  const filteredShipments = shipments.filter((shipment) => {
    const matchesSearch = shipment.tracking_number.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          shipment.destination_country.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = statusFilter === "all" || shipment.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const openPaymentDialog = (shipment: Shipment) => {
    setSelectedShipment(shipment);
    setPaymentDialogOpen(true);
  };

  const handlePaymentSuccess = () => {
    fetchShipments();
    refetchBalance();
  };

  if (loading) {
    return (
      <DashboardLayout title="Shipments" description="Manage and track all your shipments">
        <ShipmentsListSkeleton />
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout title="Shipments" description="Manage and track all your shipments">
      {/* Balance Card - Responsive */}
      <Card className="mb-4 sm:mb-6 border-border/50 bg-gradient-to-r from-primary/10 to-primary/5 card-premium">
        <CardContent className="p-3 sm:p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 sm:w-10 sm:h-10 bg-primary/20 rounded-lg flex items-center justify-center flex-shrink-0">
              <Wallet className="w-4 h-4 sm:w-5 sm:h-5 text-primary" />
            </div>
            <div>
              <p className="text-xs sm:text-sm text-muted-foreground">Wallet Balance</p>
              <p className="text-lg sm:text-xl font-bold text-foreground">₦{balance.toFixed(2)}</p>
            </div>
          </div>
          <Button variant="outline" size="sm" className="w-full sm:w-auto" onClick={() => window.location.href = "/dashboard/wallet"}>
            Manage Wallet
          </Button>
        </CardContent>
      </Card>

      {/* Actions Bar - Responsive */}
      <div className="flex flex-col gap-3 sm:flex-row sm:gap-4 mb-4 sm:mb-6">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 sm:w-5 sm:h-5 text-muted-foreground" />
          <Input
            placeholder="Search tracking or destination..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9 sm:pl-10 h-9 sm:h-10 text-sm"
          />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-full sm:w-[160px] h-9 sm:h-10">
            <SelectValue placeholder="Filter status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Status</SelectItem>
            <SelectItem value="pending">Pending</SelectItem>
            <SelectItem value="in_transit">In Transit</SelectItem>
            <SelectItem value="delivered">Delivered</SelectItem>
            <SelectItem value="cancelled">Cancelled</SelectItem>
          </SelectContent>
        </Select>

        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button variant="cta" className="w-full sm:w-auto h-9 sm:h-10">
              <Plus className="w-4 h-4 sm:w-5 sm:h-5" />
              <span className="sm:inline">New Shipment</span>
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="font-heading text-2xl">Create New Shipment</DialogTitle>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-6 mt-4">
              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Origin Country</Label>
                  <Select
                    value={formData.origin_country}
                    onValueChange={(value) => setFormData({ ...formData, origin_country: value })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select country" />
                    </SelectTrigger>
                    <SelectContent>
                      {countries.map((country) => (
                        <SelectItem key={country} value={country}>{country}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Origin City</Label>
                  <Input
                    value={formData.origin_city}
                    onChange={(e) => setFormData({ ...formData, origin_city: e.target.value })}
                    placeholder="Enter city"
                    required
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Destination Country</Label>
                  <Select
                    value={formData.destination_country}
                    onValueChange={(value) => setFormData({ ...formData, destination_country: value })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select country" />
                    </SelectTrigger>
                    <SelectContent>
                      {countries.map((country) => (
                        <SelectItem key={country} value={country}>{country}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Destination City</Label>
                  <Input
                    value={formData.destination_city}
                    onChange={(e) => setFormData({ ...formData, destination_city: e.target.value })}
                    placeholder="Enter city"
                    required
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Weight (KG)</Label>
                  <Input
                    type="number"
                    min="0.1"
                    step="0.1"
                    value={formData.weight}
                    onChange={(e) => setFormData({ ...formData, weight: e.target.value })}
                    placeholder="Enter weight"
                    required
                  />
                </div>
                <div className="space-y-2">
                  <Label>Service Type</Label>
                  <Select
                    value={formData.service_type}
                    onValueChange={(value) => setFormData({ ...formData, service_type: value })}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select service" />
                    </SelectTrigger>
                    <SelectContent>
                      {serviceTypes.map((type) => (
                        <SelectItem key={type.id} value={type.id}>{type.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label>Description (Optional)</Label>
                <Textarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Describe the contents of your shipment"
                  rows={3}
                />
              </div>

              <Button type="submit" variant="cta" className="w-full" disabled={isSubmitting}>
                {isSubmitting ? (
                  <div className="w-5 h-5 border-2 border-secondary-foreground/30 border-t-secondary-foreground rounded-full animate-spin" />
                ) : (
                  "Create Shipment"
                )}
              </Button>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {/* Shipments List */}
      {loading ? (
        <div className="flex items-center justify-center py-12">
          <div className="w-8 h-8 border-4 border-secondary/30 border-t-secondary rounded-full animate-spin" />
        </div>
      ) : filteredShipments.length > 0 ? (
        <div className="grid gap-4">
          {filteredShipments.map((shipment) => (
            <Card key={shipment.id} className="border-border/50 hover:shadow-card transition-shadow">
              <CardContent className="p-6">
                <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center flex-shrink-0">
                      <Package className="w-6 h-6 text-primary" />
                    </div>
                    <div>
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="font-semibold text-foreground">{shipment.tracking_number}</h3>
                        {getStatusBadge(shipment.status)}
                      </div>
                      <div className="flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <MapPin className="w-4 h-4" />
                          {shipment.origin_city}, {shipment.origin_country} → {shipment.destination_city}, {shipment.destination_country}
                        </span>
                        <span className="flex items-center gap-1">
                          <Package className="w-4 h-4" />
                          {shipment.weight} KG
                        </span>
                        {shipment.estimated_delivery && (
                          <span className="flex items-center gap-1">
                            <Calendar className="w-4 h-4" />
                            Est: {new Date(shipment.estimated_delivery).toLocaleDateString()}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="text-right space-y-2">
                    {shipment.price !== null && (
                      <div className="flex items-center justify-end gap-2">
                        <span className="font-semibold text-foreground">₦{Number(shipment.price).toFixed(2)}</span>
                        {shipment.payment_status === "paid" ? (
                          <Badge variant="outline" className="bg-green-500/10 text-green-600 border-green-500/30">
                            Paid
                          </Badge>
                        ) : (
                          <Button
                            size="sm"
                            variant="cta"
                            onClick={() => openPaymentDialog(shipment)}
                          >
                            <DollarSign className="w-4 h-4 mr-1" />
                            Pay Now
                          </Button>
                        )}
                      </div>
                    )}
                    {shipment.price === null && (
                      <Badge variant="secondary" className="text-xs">
                        Price Pending
                      </Badge>
                    )}
                    <p className="text-sm text-muted-foreground">
                      Created {new Date(shipment.created_at).toLocaleDateString()}
                    </p>
                    <Badge variant="outline" className="capitalize">
                      {shipment.service_type.replace("-", " ")}
                    </Badge>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card className="border-border/50">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <Package className="w-16 h-16 text-muted-foreground mb-4" />
            <h3 className="font-heading text-xl font-semibold text-foreground mb-2">No Shipments Found</h3>
            <p className="text-muted-foreground mb-4">
              {searchQuery || statusFilter !== "all"
                ? "Try adjusting your search or filters"
                : "Create your first shipment to get started"}
            </p>
            {!searchQuery && statusFilter === "all" && (
              <Button variant="cta" onClick={() => setIsDialogOpen(true)}>
                <Plus className="w-5 h-5" />
                Create Shipment
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      {/* Payment Dialog */}
      {selectedShipment && selectedShipment.price !== null && (
        <PayShipmentDialog
          open={paymentDialogOpen}
          onOpenChange={setPaymentDialogOpen}
          shipmentId={selectedShipment.id}
          trackingNumber={selectedShipment.tracking_number}
          price={Number(selectedShipment.price)}
          userBalance={balance}
          userId={user?.id || ""}
          onSuccess={handlePaymentSuccess}
        />
      )}
    </DashboardLayout>
  );
};

export default Shipments;
